name: chooz

services:
  db:
    image: postgres:17
    container_name: chooz-postgres-dev
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - chooz_pg_data:/var/lib/postgresql/data

volumes:
  chooz_pg_data: